package br.com.ccrs.logistics.fleet.order.acceptance.model;

public enum OrderProperty {
    OPTIMIZABLE,
    CAN_GENERATE_COMPLEMENT,
    CAN_GENERATE_OCCURRENCES,
    TIMEOUT_TO_ALLOCATE,
    TIMEOUT_TO_COMPLETE,
    COMPLETE_MANUALLY,
    FREIGHT_REQUIRED,
    REQUIRES_PAYMENT,
    HAS_DEFAULT_MARKET_PLACE_REGION,
    CAN_ACCEPT_ORIGIN_WITH_DEFAULT_REGION,
    SEND_CREATION_EVENTS,
    NEEDS_PAYMENT_TYPE_CHECK,
    NEEDS_DESTINATION_REGION_CHECK
}
